// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.3
// source: bonus-service.proto

package bonus

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BonusClient is the client API for Bonus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BonusClient interface {
	// Sends GetOdds status request
	AwardBonus(ctx context.Context, in *AwardBonusRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
	PlaceBonusBet(ctx context.Context, in *UserBet, opts ...grpc.CallOption) (*PlaceBetResponse, error)
	UpdateBetID(ctx context.Context, in *UpdateBetIDRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
	DebitBonus(ctx context.Context, in *BonusDebitRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
	BonusBalance(ctx context.Context, in *BonusBalanceRequest, opts ...grpc.CallOption) (*BonusBalanceResponse, error)
	Ping(ctx context.Context, in *BonusPing, opts ...grpc.CallOption) (*BonusPong, error)
}

type bonusClient struct {
	cc grpc.ClientConnInterface
}

func NewBonusClient(cc grpc.ClientConnInterface) BonusClient {
	return &bonusClient{cc}
}

func (c *bonusClient) AwardBonus(ctx context.Context, in *AwardBonusRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Bonus/AwardBonus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusClient) PlaceBonusBet(ctx context.Context, in *UserBet, opts ...grpc.CallOption) (*PlaceBetResponse, error) {
	out := new(PlaceBetResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Bonus/PlaceBonusBet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusClient) UpdateBetID(ctx context.Context, in *UpdateBetIDRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Bonus/UpdateBetID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusClient) DebitBonus(ctx context.Context, in *BonusDebitRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Bonus/DebitBonus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusClient) BonusBalance(ctx context.Context, in *BonusBalanceRequest, opts ...grpc.CallOption) (*BonusBalanceResponse, error) {
	out := new(BonusBalanceResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Bonus/BonusBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bonusClient) Ping(ctx context.Context, in *BonusPing, opts ...grpc.CallOption) (*BonusPong, error) {
	out := new(BonusPong)
	err := c.cc.Invoke(ctx, "/protobuf.Bonus/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BonusServer is the server API for Bonus service.
// All implementations must embed UnimplementedBonusServer
// for forward compatibility
type BonusServer interface {
	// Sends GetOdds status request
	AwardBonus(context.Context, *AwardBonusRequest) (*GeneralResponse, error)
	PlaceBonusBet(context.Context, *UserBet) (*PlaceBetResponse, error)
	UpdateBetID(context.Context, *UpdateBetIDRequest) (*GeneralResponse, error)
	DebitBonus(context.Context, *BonusDebitRequest) (*GeneralResponse, error)
	BonusBalance(context.Context, *BonusBalanceRequest) (*BonusBalanceResponse, error)
	Ping(context.Context, *BonusPing) (*BonusPong, error)
	mustEmbedUnimplementedBonusServer()
}

// UnimplementedBonusServer must be embedded to have forward compatible implementations.
type UnimplementedBonusServer struct {
}

func (UnimplementedBonusServer) AwardBonus(context.Context, *AwardBonusRequest) (*GeneralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AwardBonus not implemented")
}
func (UnimplementedBonusServer) PlaceBonusBet(context.Context, *UserBet) (*PlaceBetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlaceBonusBet not implemented")
}
func (UnimplementedBonusServer) UpdateBetID(context.Context, *UpdateBetIDRequest) (*GeneralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBetID not implemented")
}
func (UnimplementedBonusServer) DebitBonus(context.Context, *BonusDebitRequest) (*GeneralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DebitBonus not implemented")
}
func (UnimplementedBonusServer) BonusBalance(context.Context, *BonusBalanceRequest) (*BonusBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BonusBalance not implemented")
}
func (UnimplementedBonusServer) Ping(context.Context, *BonusPing) (*BonusPong, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedBonusServer) mustEmbedUnimplementedBonusServer() {}

// UnsafeBonusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BonusServer will
// result in compilation errors.
type UnsafeBonusServer interface {
	mustEmbedUnimplementedBonusServer()
}

func RegisterBonusServer(s grpc.ServiceRegistrar, srv BonusServer) {
	s.RegisterService(&Bonus_ServiceDesc, srv)
}

func _Bonus_AwardBonus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AwardBonusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServer).AwardBonus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Bonus/AwardBonus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServer).AwardBonus(ctx, req.(*AwardBonusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bonus_PlaceBonusBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserBet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServer).PlaceBonusBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Bonus/PlaceBonusBet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServer).PlaceBonusBet(ctx, req.(*UserBet))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bonus_UpdateBetID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBetIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServer).UpdateBetID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Bonus/UpdateBetID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServer).UpdateBetID(ctx, req.(*UpdateBetIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bonus_DebitBonus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BonusDebitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServer).DebitBonus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Bonus/DebitBonus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServer).DebitBonus(ctx, req.(*BonusDebitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bonus_BonusBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BonusBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServer).BonusBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Bonus/BonusBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServer).BonusBalance(ctx, req.(*BonusBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bonus_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BonusPing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Bonus/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServer).Ping(ctx, req.(*BonusPing))
	}
	return interceptor(ctx, in, info, handler)
}

// Bonus_ServiceDesc is the grpc.ServiceDesc for Bonus service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bonus_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Bonus",
	HandlerType: (*BonusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AwardBonus",
			Handler:    _Bonus_AwardBonus_Handler,
		},
		{
			MethodName: "PlaceBonusBet",
			Handler:    _Bonus_PlaceBonusBet_Handler,
		},
		{
			MethodName: "UpdateBetID",
			Handler:    _Bonus_UpdateBetID_Handler,
		},
		{
			MethodName: "DebitBonus",
			Handler:    _Bonus_DebitBonus_Handler,
		},
		{
			MethodName: "BonusBalance",
			Handler:    _Bonus_BonusBalance_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Bonus_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bonus-service.proto",
}
