// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v5.29.3
// source: betting-service.proto

package betting

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BettingPing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BettingPing) Reset() {
	*x = BettingPing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_betting_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BettingPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BettingPing) ProtoMessage() {}

func (x *BettingPing) ProtoReflect() protoreflect.Message {
	mi := &file_betting_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BettingPing.ProtoReflect.Descriptor instead.
func (*BettingPing) Descriptor() ([]byte, []int) {
	return file_betting_service_proto_rawDescGZIP(), []int{0}
}

type BettingPong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Data   string `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *BettingPong) Reset() {
	*x = BettingPong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_betting_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BettingPong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BettingPong) ProtoMessage() {}

func (x *BettingPong) ProtoReflect() protoreflect.Message {
	mi := &file_betting_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BettingPong.ProtoReflect.Descriptor instead.
func (*BettingPong) Descriptor() ([]byte, []int) {
	return file_betting_service_proto_rawDescGZIP(), []int{1}
}

func (x *BettingPong) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *BettingPong) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// The request message containing the selection details.
type BetSummaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProfileID int32 `protobuf:"varint,1,opt,name=profileID,proto3" json:"profileID,omitempty"`
}

func (x *BetSummaryRequest) Reset() {
	*x = BetSummaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_betting_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BetSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetSummaryRequest) ProtoMessage() {}

func (x *BetSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_betting_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetSummaryRequest.ProtoReflect.Descriptor instead.
func (*BetSummaryRequest) Descriptor() ([]byte, []int) {
	return file_betting_service_proto_rawDescGZIP(), []int{2}
}

func (x *BetSummaryRequest) GetProfileID() int32 {
	if x != nil {
		return x.ProfileID
	}
	return 0
}

type BetSummaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumberOfBets int32   `protobuf:"varint,1,opt,name=NumberOfBets,proto3" json:"NumberOfBets,omitempty"`
	Stake        float32 `protobuf:"fixed32,2,opt,name=Stake,proto3" json:"Stake,omitempty"`
	Winning      float32 `protobuf:"fixed32,3,opt,name=Winning,proto3" json:"Winning,omitempty"`
}

func (x *BetSummaryResponse) Reset() {
	*x = BetSummaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_betting_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BetSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetSummaryResponse) ProtoMessage() {}

func (x *BetSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_betting_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetSummaryResponse.ProtoReflect.Descriptor instead.
func (*BetSummaryResponse) Descriptor() ([]byte, []int) {
	return file_betting_service_proto_rawDescGZIP(), []int{3}
}

func (x *BetSummaryResponse) GetNumberOfBets() int32 {
	if x != nil {
		return x.NumberOfBets
	}
	return 0
}

func (x *BetSummaryResponse) GetStake() float32 {
	if x != nil {
		return x.Stake
	}
	return 0
}

func (x *BetSummaryResponse) GetWinning() float32 {
	if x != nil {
		return x.Winning
	}
	return 0
}

type BetStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProfileID int64  `protobuf:"varint,1,opt,name=profileID,proto3" json:"profileID,omitempty"`
	ShareCode string `protobuf:"bytes,2,opt,name=ShareCode,proto3" json:"ShareCode,omitempty"`
}

func (x *BetStatusRequest) Reset() {
	*x = BetStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_betting_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetStatusRequest) ProtoMessage() {}

func (x *BetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_betting_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetStatusRequest.ProtoReflect.Descriptor instead.
func (*BetStatusRequest) Descriptor() ([]byte, []int) {
	return file_betting_service_proto_rawDescGZIP(), []int{4}
}

func (x *BetStatusRequest) GetProfileID() int64 {
	if x != nil {
		return x.ProfileID
	}
	return 0
}

func (x *BetStatusRequest) GetShareCode() string {
	if x != nil {
		return x.ShareCode
	}
	return ""
}

type SelectedSlips struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchName   string `protobuf:"bytes,1,opt,name=MatchName,proto3" json:"MatchName,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	Status      int64  `protobuf:"varint,3,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *SelectedSlips) Reset() {
	*x = SelectedSlips{}
	if protoimpl.UnsafeEnabled {
		mi := &file_betting_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectedSlips) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectedSlips) ProtoMessage() {}

func (x *SelectedSlips) ProtoReflect() protoreflect.Message {
	mi := &file_betting_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectedSlips.ProtoReflect.Descriptor instead.
func (*SelectedSlips) Descriptor() ([]byte, []int) {
	return file_betting_service_proto_rawDescGZIP(), []int{5}
}

func (x *SelectedSlips) GetMatchName() string {
	if x != nil {
		return x.MatchName
	}
	return ""
}

func (x *SelectedSlips) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SelectedSlips) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type BetStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID            int64            `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Description   string           `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	Status        int64            `protobuf:"varint,3,opt,name=Status,proto3" json:"Status,omitempty"`
	Payout        float32          `protobuf:"fixed32,4,opt,name=Payout,proto3" json:"Payout,omitempty"`
	SelectedSlips []*SelectedSlips `protobuf:"bytes,5,rep,name=SelectedSlips,proto3" json:"SelectedSlips,omitempty"`
}

func (x *BetStatusResponse) Reset() {
	*x = BetStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_betting_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetStatusResponse) ProtoMessage() {}

func (x *BetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_betting_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetStatusResponse.ProtoReflect.Descriptor instead.
func (*BetStatusResponse) Descriptor() ([]byte, []int) {
	return file_betting_service_proto_rawDescGZIP(), []int{6}
}

func (x *BetStatusResponse) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *BetStatusResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BetStatusResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *BetStatusResponse) GetPayout() float32 {
	if x != nil {
		return x.Payout
	}
	return 0
}

func (x *BetStatusResponse) GetSelectedSlips() []*SelectedSlips {
	if x != nil {
		return x.SelectedSlips
	}
	return nil
}

type PlaceBetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slips       []*Slips `protobuf:"bytes,1,rep,name=slips,proto3" json:"slips,omitempty"`
	ProfileID   int64    `protobuf:"varint,2,opt,name=ProfileID,proto3" json:"ProfileID,omitempty"`
	Stake       float32  `protobuf:"fixed32,3,opt,name=stake,proto3" json:"stake,omitempty"`
	Source      string   `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	IpAddress   string   `protobuf:"bytes,5,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	BetType     int64    `protobuf:"varint,6,opt,name=betType,proto3" json:"betType,omitempty"`
	BookingCode string   `protobuf:"bytes,7,opt,name=BookingCode,proto3" json:"BookingCode,omitempty"`
	ChannelID   int64    `protobuf:"varint,8,opt,name=ChannelID,proto3" json:"ChannelID,omitempty"`
}

func (x *PlaceBetRequest) Reset() {
	*x = PlaceBetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_betting_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaceBetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceBetRequest) ProtoMessage() {}

func (x *PlaceBetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_betting_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceBetRequest.ProtoReflect.Descriptor instead.
func (*PlaceBetRequest) Descriptor() ([]byte, []int) {
	return file_betting_service_proto_rawDescGZIP(), []int{7}
}

func (x *PlaceBetRequest) GetSlips() []*Slips {
	if x != nil {
		return x.Slips
	}
	return nil
}

func (x *PlaceBetRequest) GetProfileID() int64 {
	if x != nil {
		return x.ProfileID
	}
	return 0
}

func (x *PlaceBetRequest) GetStake() float32 {
	if x != nil {
		return x.Stake
	}
	return 0
}

func (x *PlaceBetRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PlaceBetRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *PlaceBetRequest) GetBetType() int64 {
	if x != nil {
		return x.BetType
	}
	return 0
}

func (x *PlaceBetRequest) GetBookingCode() string {
	if x != nil {
		return x.BookingCode
	}
	return ""
}

func (x *PlaceBetRequest) GetChannelID() int64 {
	if x != nil {
		return x.ChannelID
	}
	return 0
}

type CancelBetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShareCode string `protobuf:"bytes,1,opt,name=shareCode,proto3" json:"shareCode,omitempty"`
	ProfileID int64  `protobuf:"varint,2,opt,name=ProfileID,proto3" json:"ProfileID,omitempty"`
	MSISDN    int64  `protobuf:"varint,3,opt,name=MSISDN,proto3" json:"MSISDN,omitempty"`
	IpAddress string `protobuf:"bytes,4,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
}

func (x *CancelBetRequest) Reset() {
	*x = CancelBetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_betting_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelBetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBetRequest) ProtoMessage() {}

func (x *CancelBetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_betting_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBetRequest.ProtoReflect.Descriptor instead.
func (*CancelBetRequest) Descriptor() ([]byte, []int) {
	return file_betting_service_proto_rawDescGZIP(), []int{8}
}

func (x *CancelBetRequest) GetShareCode() string {
	if x != nil {
		return x.ShareCode
	}
	return ""
}

func (x *CancelBetRequest) GetProfileID() int64 {
	if x != nil {
		return x.ProfileID
	}
	return 0
}

func (x *CancelBetRequest) GetMSISDN() int64 {
	if x != nil {
		return x.MSISDN
	}
	return 0
}

func (x *CancelBetRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type CashOutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BetId  int64   `protobuf:"varint,1,opt,name=BetId,proto3" json:"BetId,omitempty"`
	Amount float32 `protobuf:"fixed32,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
}

func (x *CashOutRequest) Reset() {
	*x = CashOutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_betting_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CashOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashOutRequest) ProtoMessage() {}

func (x *CashOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_betting_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashOutRequest.ProtoReflect.Descriptor instead.
func (*CashOutRequest) Descriptor() ([]byte, []int) {
	return file_betting_service_proto_rawDescGZIP(), []int{9}
}

func (x *CashOutRequest) GetBetId() int64 {
	if x != nil {
		return x.BetId
	}
	return 0
}

func (x *CashOutRequest) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type Slips struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProducerID int64  `protobuf:"varint,1,opt,name=ProducerID,proto3" json:"ProducerID,omitempty"`
	MatchID    int64  `protobuf:"varint,2,opt,name=MatchID,proto3" json:"MatchID,omitempty"`
	MarketID   int64  `protobuf:"varint,3,opt,name=MarketID,proto3" json:"MarketID,omitempty"`
	Specifier  string `protobuf:"bytes,4,opt,name=Specifier,proto3" json:"Specifier,omitempty"`
	OutcomeID  string `protobuf:"bytes,5,opt,name=OutcomeID,proto3" json:"OutcomeID,omitempty"`
}

func (x *Slips) Reset() {
	*x = Slips{}
	if protoimpl.UnsafeEnabled {
		mi := &file_betting_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Slips) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slips) ProtoMessage() {}

func (x *Slips) ProtoReflect() protoreflect.Message {
	mi := &file_betting_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slips.ProtoReflect.Descriptor instead.
func (*Slips) Descriptor() ([]byte, []int) {
	return file_betting_service_proto_rawDescGZIP(), []int{10}
}

func (x *Slips) GetProducerID() int64 {
	if x != nil {
		return x.ProducerID
	}
	return 0
}

func (x *Slips) GetMatchID() int64 {
	if x != nil {
		return x.MatchID
	}
	return 0
}

func (x *Slips) GetMarketID() int64 {
	if x != nil {
		return x.MarketID
	}
	return 0
}

func (x *Slips) GetSpecifier() string {
	if x != nil {
		return x.Specifier
	}
	return ""
}

func (x *Slips) GetOutcomeID() string {
	if x != nil {
		return x.OutcomeID
	}
	return ""
}

type PlaceBetResponseMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status      int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ShareCode   string `protobuf:"bytes,3,opt,name=shareCode,proto3" json:"shareCode,omitempty"`
}

func (x *PlaceBetResponseMessage) Reset() {
	*x = PlaceBetResponseMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_betting_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaceBetResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceBetResponseMessage) ProtoMessage() {}

func (x *PlaceBetResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_betting_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceBetResponseMessage.ProtoReflect.Descriptor instead.
func (*PlaceBetResponseMessage) Descriptor() ([]byte, []int) {
	return file_betting_service_proto_rawDescGZIP(), []int{11}
}

func (x *PlaceBetResponseMessage) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PlaceBetResponseMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PlaceBetResponseMessage) GetShareCode() string {
	if x != nil {
		return x.ShareCode
	}
	return ""
}

type CancelBetResponseMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status      int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *CancelBetResponseMessage) Reset() {
	*x = CancelBetResponseMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_betting_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelBetResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBetResponseMessage) ProtoMessage() {}

func (x *CancelBetResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_betting_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBetResponseMessage.ProtoReflect.Descriptor instead.
func (*CancelBetResponseMessage) Descriptor() ([]byte, []int) {
	return file_betting_service_proto_rawDescGZIP(), []int{12}
}

func (x *CancelBetResponseMessage) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CancelBetResponseMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CashOutResponseMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status      int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *CashOutResponseMessage) Reset() {
	*x = CashOutResponseMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_betting_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CashOutResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashOutResponseMessage) ProtoMessage() {}

func (x *CashOutResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_betting_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashOutResponseMessage.ProtoReflect.Descriptor instead.
func (*CashOutResponseMessage) Descriptor() ([]byte, []int) {
	return file_betting_service_proto_rawDescGZIP(), []int{13}
}

func (x *CashOutResponseMessage) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CashOutResponseMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CashBackRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProfileId int64 `protobuf:"varint,1,opt,name=profileId,proto3" json:"profileId,omitempty"`
}

func (x *CashBackRequest) Reset() {
	*x = CashBackRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_betting_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CashBackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashBackRequest) ProtoMessage() {}

func (x *CashBackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_betting_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashBackRequest.ProtoReflect.Descriptor instead.
func (*CashBackRequest) Descriptor() ([]byte, []int) {
	return file_betting_service_proto_rawDescGZIP(), []int{14}
}

func (x *CashBackRequest) GetProfileId() int64 {
	if x != nil {
		return x.ProfileId
	}
	return 0
}

type CashbackResponseMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Awarded bool `protobuf:"varint,1,opt,name=awarded,proto3" json:"awarded,omitempty"`
}

func (x *CashbackResponseMessage) Reset() {
	*x = CashbackResponseMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_betting_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CashbackResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashbackResponseMessage) ProtoMessage() {}

func (x *CashbackResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_betting_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashbackResponseMessage.ProtoReflect.Descriptor instead.
func (*CashbackResponseMessage) Descriptor() ([]byte, []int) {
	return file_betting_service_proto_rawDescGZIP(), []int{15}
}

func (x *CashbackResponseMessage) GetAwarded() bool {
	if x != nil {
		return x.Awarded
	}
	return false
}

type MTSResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code        int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	BetID       string `protobuf:"bytes,3,opt,name=betID,proto3" json:"betID,omitempty"`
}

func (x *MTSResponse) Reset() {
	*x = MTSResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_betting_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MTSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MTSResponse) ProtoMessage() {}

func (x *MTSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_betting_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MTSResponse.ProtoReflect.Descriptor instead.
func (*MTSResponse) Descriptor() ([]byte, []int) {
	return file_betting_service_proto_rawDescGZIP(), []int{16}
}

func (x *MTSResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MTSResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MTSResponse) GetBetID() string {
	if x != nil {
		return x.BetID
	}
	return ""
}

type GeneralAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *GeneralAck) Reset() {
	*x = GeneralAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_betting_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeneralAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralAck) ProtoMessage() {}

func (x *GeneralAck) ProtoReflect() protoreflect.Message {
	mi := &file_betting_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralAck.ProtoReflect.Descriptor instead.
func (*GeneralAck) Descriptor() ([]byte, []int) {
	return file_betting_service_proto_rawDescGZIP(), []int{17}
}

func (x *GeneralAck) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type MTSConnectionStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status      int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *MTSConnectionStatus) Reset() {
	*x = MTSConnectionStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_betting_service_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MTSConnectionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MTSConnectionStatus) ProtoMessage() {}

func (x *MTSConnectionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_betting_service_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MTSConnectionStatus.ProtoReflect.Descriptor instead.
func (*MTSConnectionStatus) Descriptor() ([]byte, []int) {
	return file_betting_service_proto_rawDescGZIP(), []int{18}
}

func (x *MTSConnectionStatus) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MTSConnectionStatus) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_betting_service_proto protoreflect.FileDescriptor

var file_betting_service_proto_rawDesc = []byte{
	0x0a, 0x15, 0x62, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x22, 0x0d, 0x0a, 0x0b, 0x42, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x50, 0x69, 0x6e, 0x67,
	0x22, 0x39, 0x0a, 0x0b, 0x42, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x6e, 0x67, 0x12,
	0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x31, 0x0a, 0x11, 0x42,
	0x65, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x44, 0x22, 0x68,
	0x0a, 0x12, 0x42, 0x65, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66,
	0x42, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x4f, 0x66, 0x42, 0x65, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x6b,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x53, 0x74, 0x61, 0x6b, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x57, 0x69, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x07, 0x57, 0x69, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x22, 0x4e, 0x0a, 0x10, 0x42, 0x65, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x68,
	0x61, 0x72, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53,
	0x68, 0x61, 0x72, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x67, 0x0a, 0x0d, 0x53, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x65, 0x64, 0x53, 0x6c, 0x69, 0x70, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x61, 0x74,
	0x63, 0x68, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0xb4, 0x01, 0x0a, 0x11, 0x42, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x06, 0x50, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x12, 0x3d, 0x0a, 0x0d, 0x53, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x65, 0x64, 0x53, 0x6c, 0x69, 0x70, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x65, 0x64, 0x53, 0x6c, 0x69, 0x70, 0x73, 0x52, 0x0d, 0x53, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x53, 0x6c, 0x69, 0x70, 0x73, 0x22, 0xfc, 0x01, 0x0a, 0x0f, 0x50, 0x6c, 0x61,
	0x63, 0x65, 0x42, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x05,
	0x73, 0x6c, 0x69, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x6c, 0x69, 0x70, 0x73, 0x52, 0x05, 0x73, 0x6c,
	0x69, 0x70, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49,
	0x44, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x6b, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x6b, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x69, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x69, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x62, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x62, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x42, 0x6f, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x42, 0x6f,
	0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x44, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x44, 0x22, 0x84, 0x01, 0x0a, 0x10, 0x43, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x42, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x68, 0x61, 0x72, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x50,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x53, 0x49, 0x53,
	0x44, 0x4e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x4d, 0x53, 0x49, 0x53, 0x44, 0x4e,
	0x12, 0x1c, 0x0a, 0x09, 0x69, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x3e,
	0x0a, 0x0e, 0x43, 0x61, 0x73, 0x68, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x42, 0x65, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x42, 0x65, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x99,
	0x01, 0x0a, 0x05, 0x53, 0x6c, 0x69, 0x70, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x61, 0x74, 0x63,
	0x68, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x49, 0x44, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x49, 0x44, 0x12, 0x1c,
	0x0a, 0x09, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09,
	0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x49, 0x44, 0x22, 0x71, 0x0a, 0x17, 0x50, 0x6c,
	0x61, 0x63, 0x65, 0x42, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x68, 0x61, 0x72, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x61, 0x72, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x54, 0x0a,
	0x18, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x42, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x52, 0x0a, 0x16, 0x43, 0x61, 0x73, 0x68, 0x4f, 0x75, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2f, 0x0a, 0x0f, 0x43, 0x61, 0x73, 0x68, 0x42,
	0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x70,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x33, 0x0a, 0x17, 0x43, 0x61, 0x73, 0x68,
	0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x77, 0x61, 0x72, 0x64, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x61, 0x77, 0x61, 0x72, 0x64, 0x65, 0x64, 0x22, 0x59, 0x0a,
	0x0b, 0x4d, 0x54, 0x53, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x65, 0x74, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x62, 0x65, 0x74, 0x49, 0x44, 0x22, 0x2e, 0x0a, 0x0a, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x6c, 0x41, 0x63, 0x6b, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4f, 0x0a, 0x13, 0x4d, 0x54, 0x53, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x86, 0x07, 0x0a, 0x07, 0x42, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x49, 0x0a, 0x0a, 0x42, 0x65, 0x74, 0x53, 0x75, 0x6d, 0x6d,
	0x61, 0x72, 0x79, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42,
	0x65, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x65, 0x74, 0x53,
	0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x36, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x42, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x50, 0x69, 0x6e, 0x67, 0x1a,
	0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x50, 0x6f, 0x6e, 0x67, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x09, 0x42, 0x65, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x42, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x65, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x4a, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x42, 0x65, 0x74, 0x12, 0x19, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x42, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x42, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x07,
	0x43, 0x61, 0x73, 0x68, 0x4f, 0x75, 0x74, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x43, 0x61, 0x73, 0x68, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x43, 0x61, 0x73,
	0x68, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x09, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x42,
	0x65, 0x74, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x43, 0x61,
	0x6e, 0x63, 0x65, 0x6c, 0x42, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c,
	0x42, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x0f, 0x41, 0x77, 0x61, 0x72, 0x64, 0x65, 0x64, 0x43,
	0x61, 0x73, 0x68, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x43, 0x61, 0x73, 0x68, 0x42, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x43, 0x61,
	0x73, 0x68, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x13, 0x42, 0x65, 0x74, 0x41, 0x63,
	0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x15,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x54, 0x53, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x41, 0x63, 0x6b, 0x22, 0x00, 0x12, 0x45, 0x0a,
	0x14, 0x42, 0x65, 0x74, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x4d, 0x54, 0x53, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x14, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x41,
	0x63, 0x6b, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x19, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x42, 0x65,
	0x74, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x54, 0x53,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x41, 0x63, 0x6b, 0x22, 0x00,
	0x12, 0x4a, 0x0a, 0x19, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x42, 0x65, 0x74, 0x52, 0x65, 0x6a,
	0x65, 0x63, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x15, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x54, 0x53, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x41, 0x63, 0x6b, 0x22, 0x00, 0x12, 0x54, 0x0a, 0x1b,
	0x4d, 0x74, 0x73, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x54, 0x53, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x41, 0x63, 0x6b,
	0x22, 0x00, 0x42, 0x38, 0x5a, 0x36, 0x62, 0x69, 0x74, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x2e,
	0x6f, 0x72, 0x67, 0x2f, 0x6d, 0x61, 0x79, 0x62, 0x65, 0x74, 0x73, 0x2f, 0x62, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x70, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x62, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_betting_service_proto_rawDescOnce sync.Once
	file_betting_service_proto_rawDescData = file_betting_service_proto_rawDesc
)

func file_betting_service_proto_rawDescGZIP() []byte {
	file_betting_service_proto_rawDescOnce.Do(func() {
		file_betting_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_betting_service_proto_rawDescData)
	})
	return file_betting_service_proto_rawDescData
}

var file_betting_service_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_betting_service_proto_goTypes = []interface{}{
	(*BettingPing)(nil),              // 0: protobuf.BettingPing
	(*BettingPong)(nil),              // 1: protobuf.BettingPong
	(*BetSummaryRequest)(nil),        // 2: protobuf.BetSummaryRequest
	(*BetSummaryResponse)(nil),       // 3: protobuf.BetSummaryResponse
	(*BetStatusRequest)(nil),         // 4: protobuf.BetStatusRequest
	(*SelectedSlips)(nil),            // 5: protobuf.SelectedSlips
	(*BetStatusResponse)(nil),        // 6: protobuf.BetStatusResponse
	(*PlaceBetRequest)(nil),          // 7: protobuf.PlaceBetRequest
	(*CancelBetRequest)(nil),         // 8: protobuf.CancelBetRequest
	(*CashOutRequest)(nil),           // 9: protobuf.CashOutRequest
	(*Slips)(nil),                    // 10: protobuf.Slips
	(*PlaceBetResponseMessage)(nil),  // 11: protobuf.PlaceBetResponseMessage
	(*CancelBetResponseMessage)(nil), // 12: protobuf.CancelBetResponseMessage
	(*CashOutResponseMessage)(nil),   // 13: protobuf.CashOutResponseMessage
	(*CashBackRequest)(nil),          // 14: protobuf.CashBackRequest
	(*CashbackResponseMessage)(nil),  // 15: protobuf.CashbackResponseMessage
	(*MTSResponse)(nil),              // 16: protobuf.MTSResponse
	(*GeneralAck)(nil),               // 17: protobuf.GeneralAck
	(*MTSConnectionStatus)(nil),      // 18: protobuf.MTSConnectionStatus
}
var file_betting_service_proto_depIdxs = []int32{
	5,  // 0: protobuf.BetStatusResponse.SelectedSlips:type_name -> protobuf.SelectedSlips
	10, // 1: protobuf.PlaceBetRequest.slips:type_name -> protobuf.Slips
	2,  // 2: protobuf.Betting.BetSummary:input_type -> protobuf.BetSummaryRequest
	0,  // 3: protobuf.Betting.Ping:input_type -> protobuf.BettingPing
	4,  // 4: protobuf.Betting.BetStatus:input_type -> protobuf.BetStatusRequest
	7,  // 5: protobuf.Betting.PlaceBet:input_type -> protobuf.PlaceBetRequest
	9,  // 6: protobuf.Betting.CashOut:input_type -> protobuf.CashOutRequest
	8,  // 7: protobuf.Betting.CancelBet:input_type -> protobuf.CancelBetRequest
	14, // 8: protobuf.Betting.AwardedCashback:input_type -> protobuf.CashBackRequest
	16, // 9: protobuf.Betting.BetAcceptedResponse:input_type -> protobuf.MTSResponse
	16, // 10: protobuf.Betting.BetCancelledResponse:input_type -> protobuf.MTSResponse
	16, // 11: protobuf.Betting.CancelBetAcceptedResponse:input_type -> protobuf.MTSResponse
	16, // 12: protobuf.Betting.CancelBetRejectedResponse:input_type -> protobuf.MTSResponse
	18, // 13: protobuf.Betting.MtsConnectionChangeResponse:input_type -> protobuf.MTSConnectionStatus
	3,  // 14: protobuf.Betting.BetSummary:output_type -> protobuf.BetSummaryResponse
	1,  // 15: protobuf.Betting.Ping:output_type -> protobuf.BettingPong
	6,  // 16: protobuf.Betting.BetStatus:output_type -> protobuf.BetStatusResponse
	11, // 17: protobuf.Betting.PlaceBet:output_type -> protobuf.PlaceBetResponseMessage
	13, // 18: protobuf.Betting.CashOut:output_type -> protobuf.CashOutResponseMessage
	12, // 19: protobuf.Betting.CancelBet:output_type -> protobuf.CancelBetResponseMessage
	15, // 20: protobuf.Betting.AwardedCashback:output_type -> protobuf.CashbackResponseMessage
	17, // 21: protobuf.Betting.BetAcceptedResponse:output_type -> protobuf.GeneralAck
	17, // 22: protobuf.Betting.BetCancelledResponse:output_type -> protobuf.GeneralAck
	17, // 23: protobuf.Betting.CancelBetAcceptedResponse:output_type -> protobuf.GeneralAck
	17, // 24: protobuf.Betting.CancelBetRejectedResponse:output_type -> protobuf.GeneralAck
	17, // 25: protobuf.Betting.MtsConnectionChangeResponse:output_type -> protobuf.GeneralAck
	14, // [14:26] is the sub-list for method output_type
	2,  // [2:14] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_betting_service_proto_init() }
func file_betting_service_proto_init() {
	if File_betting_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_betting_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BettingPing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_betting_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BettingPong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_betting_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BetSummaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_betting_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BetSummaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_betting_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BetStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_betting_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectedSlips); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_betting_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BetStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_betting_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaceBetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_betting_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelBetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_betting_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CashOutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_betting_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Slips); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_betting_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaceBetResponseMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_betting_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelBetResponseMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_betting_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CashOutResponseMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_betting_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CashBackRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_betting_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CashbackResponseMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_betting_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MTSResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_betting_service_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeneralAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_betting_service_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MTSConnectionStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_betting_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_betting_service_proto_goTypes,
		DependencyIndexes: file_betting_service_proto_depIdxs,
		MessageInfos:      file_betting_service_proto_msgTypes,
	}.Build()
	File_betting_service_proto = out.File
	file_betting_service_proto_rawDesc = nil
	file_betting_service_proto_goTypes = nil
	file_betting_service_proto_depIdxs = nil
}
