// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: jackpot-service.proto

package jackpot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JackpotPing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *JackpotPing) Reset() {
	*x = JackpotPing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jackpot_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JackpotPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JackpotPing) ProtoMessage() {}

func (x *JackpotPing) ProtoReflect() protoreflect.Message {
	mi := &file_jackpot_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JackpotPing.ProtoReflect.Descriptor instead.
func (*JackpotPing) Descriptor() ([]byte, []int) {
	return file_jackpot_service_proto_rawDescGZIP(), []int{0}
}

type JackpotPong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Data   string `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *JackpotPong) Reset() {
	*x = JackpotPong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jackpot_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JackpotPong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JackpotPong) ProtoMessage() {}

func (x *JackpotPong) ProtoReflect() protoreflect.Message {
	mi := &file_jackpot_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JackpotPong.ProtoReflect.Descriptor instead.
func (*JackpotPong) Descriptor() ([]byte, []int) {
	return file_jackpot_service_proto_rawDescGZIP(), []int{1}
}

func (x *JackpotPong) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *JackpotPong) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// The request message containing the selection details.
type JPBetSummaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProfileID int32 `protobuf:"varint,1,opt,name=profileID,proto3" json:"profileID,omitempty"`
}

func (x *JPBetSummaryRequest) Reset() {
	*x = JPBetSummaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jackpot_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JPBetSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JPBetSummaryRequest) ProtoMessage() {}

func (x *JPBetSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jackpot_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JPBetSummaryRequest.ProtoReflect.Descriptor instead.
func (*JPBetSummaryRequest) Descriptor() ([]byte, []int) {
	return file_jackpot_service_proto_rawDescGZIP(), []int{2}
}

func (x *JPBetSummaryRequest) GetProfileID() int32 {
	if x != nil {
		return x.ProfileID
	}
	return 0
}

type JPBetSummaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumberOfBets int32   `protobuf:"varint,1,opt,name=NumberOfBets,proto3" json:"NumberOfBets,omitempty"`
	Stake        float32 `protobuf:"fixed32,2,opt,name=Stake,proto3" json:"Stake,omitempty"`
	Winning      float32 `protobuf:"fixed32,3,opt,name=Winning,proto3" json:"Winning,omitempty"`
}

func (x *JPBetSummaryResponse) Reset() {
	*x = JPBetSummaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jackpot_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JPBetSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JPBetSummaryResponse) ProtoMessage() {}

func (x *JPBetSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jackpot_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JPBetSummaryResponse.ProtoReflect.Descriptor instead.
func (*JPBetSummaryResponse) Descriptor() ([]byte, []int) {
	return file_jackpot_service_proto_rawDescGZIP(), []int{3}
}

func (x *JPBetSummaryResponse) GetNumberOfBets() int32 {
	if x != nil {
		return x.NumberOfBets
	}
	return 0
}

func (x *JPBetSummaryResponse) GetStake() float32 {
	if x != nil {
		return x.Stake
	}
	return 0
}

func (x *JPBetSummaryResponse) GetWinning() float32 {
	if x != nil {
		return x.Winning
	}
	return 0
}

type JackpotSelectedSlips struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchName   string `protobuf:"bytes,1,opt,name=MatchName,proto3" json:"MatchName,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	Status      int64  `protobuf:"varint,3,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *JackpotSelectedSlips) Reset() {
	*x = JackpotSelectedSlips{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jackpot_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JackpotSelectedSlips) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JackpotSelectedSlips) ProtoMessage() {}

func (x *JackpotSelectedSlips) ProtoReflect() protoreflect.Message {
	mi := &file_jackpot_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JackpotSelectedSlips.ProtoReflect.Descriptor instead.
func (*JackpotSelectedSlips) Descriptor() ([]byte, []int) {
	return file_jackpot_service_proto_rawDescGZIP(), []int{4}
}

func (x *JackpotSelectedSlips) GetMatchName() string {
	if x != nil {
		return x.MatchName
	}
	return ""
}

func (x *JackpotSelectedSlips) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *JackpotSelectedSlips) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type JackpotBetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JackpotSlips []*JackpotSlips `protobuf:"bytes,1,rep,name=JackpotSlips,proto3" json:"JackpotSlips,omitempty"`
	ProfileID    int64           `protobuf:"varint,2,opt,name=ProfileID,proto3" json:"ProfileID,omitempty"`
	Stake        float32         `protobuf:"fixed32,3,opt,name=stake,proto3" json:"stake,omitempty"`
	Source       string          `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	IpAddress    string          `protobuf:"bytes,5,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	BetType      int64           `protobuf:"varint,6,opt,name=betType,proto3" json:"betType,omitempty"`
	BookingCode  string          `protobuf:"bytes,7,opt,name=BookingCode,proto3" json:"BookingCode,omitempty"`
	JackpotID    int64           `protobuf:"varint,8,opt,name=JackpotID,proto3" json:"JackpotID,omitempty"`
}

func (x *JackpotBetRequest) Reset() {
	*x = JackpotBetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jackpot_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JackpotBetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JackpotBetRequest) ProtoMessage() {}

func (x *JackpotBetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jackpot_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JackpotBetRequest.ProtoReflect.Descriptor instead.
func (*JackpotBetRequest) Descriptor() ([]byte, []int) {
	return file_jackpot_service_proto_rawDescGZIP(), []int{5}
}

func (x *JackpotBetRequest) GetJackpotSlips() []*JackpotSlips {
	if x != nil {
		return x.JackpotSlips
	}
	return nil
}

func (x *JackpotBetRequest) GetProfileID() int64 {
	if x != nil {
		return x.ProfileID
	}
	return 0
}

func (x *JackpotBetRequest) GetStake() float32 {
	if x != nil {
		return x.Stake
	}
	return 0
}

func (x *JackpotBetRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *JackpotBetRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *JackpotBetRequest) GetBetType() int64 {
	if x != nil {
		return x.BetType
	}
	return 0
}

func (x *JackpotBetRequest) GetBookingCode() string {
	if x != nil {
		return x.BookingCode
	}
	return ""
}

func (x *JackpotBetRequest) GetJackpotID() int64 {
	if x != nil {
		return x.JackpotID
	}
	return 0
}

type JackpotGamesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CategoryID int64 `protobuf:"varint,1,opt,name=CategoryID,proto3" json:"CategoryID,omitempty"`
}

func (x *JackpotGamesRequest) Reset() {
	*x = JackpotGamesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jackpot_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JackpotGamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JackpotGamesRequest) ProtoMessage() {}

func (x *JackpotGamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jackpot_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JackpotGamesRequest.ProtoReflect.Descriptor instead.
func (*JackpotGamesRequest) Descriptor() ([]byte, []int) {
	return file_jackpot_service_proto_rawDescGZIP(), []int{6}
}

func (x *JackpotGamesRequest) GetCategoryID() int64 {
	if x != nil {
		return x.CategoryID
	}
	return 0
}

type JackpotGamesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Games string `protobuf:"bytes,1,opt,name=Games,proto3" json:"Games,omitempty"`
}

func (x *JackpotGamesResponse) Reset() {
	*x = JackpotGamesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jackpot_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JackpotGamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JackpotGamesResponse) ProtoMessage() {}

func (x *JackpotGamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jackpot_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JackpotGamesResponse.ProtoReflect.Descriptor instead.
func (*JackpotGamesResponse) Descriptor() ([]byte, []int) {
	return file_jackpot_service_proto_rawDescGZIP(), []int{7}
}

func (x *JackpotGamesResponse) GetGames() string {
	if x != nil {
		return x.Games
	}
	return ""
}

type JackpotSlips struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchID     int64  `protobuf:"varint,1,opt,name=MatchID,proto3" json:"MatchID,omitempty"`
	ProducerID  int64  `protobuf:"varint,2,opt,name=ProducerID,proto3" json:"ProducerID,omitempty"`
	MatchNumber int64  `protobuf:"varint,3,opt,name=MatchNumber,proto3" json:"MatchNumber,omitempty"`
	MarketID    int64  `protobuf:"varint,4,opt,name=MarketID,proto3" json:"MarketID,omitempty"`
	OutcomeID   string `protobuf:"bytes,5,opt,name=OutcomeID,proto3" json:"OutcomeID,omitempty"`
	Specifier   string `protobuf:"bytes,6,opt,name=Specifier,proto3" json:"Specifier,omitempty"`
}

func (x *JackpotSlips) Reset() {
	*x = JackpotSlips{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jackpot_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JackpotSlips) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JackpotSlips) ProtoMessage() {}

func (x *JackpotSlips) ProtoReflect() protoreflect.Message {
	mi := &file_jackpot_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JackpotSlips.ProtoReflect.Descriptor instead.
func (*JackpotSlips) Descriptor() ([]byte, []int) {
	return file_jackpot_service_proto_rawDescGZIP(), []int{8}
}

func (x *JackpotSlips) GetMatchID() int64 {
	if x != nil {
		return x.MatchID
	}
	return 0
}

func (x *JackpotSlips) GetProducerID() int64 {
	if x != nil {
		return x.ProducerID
	}
	return 0
}

func (x *JackpotSlips) GetMatchNumber() int64 {
	if x != nil {
		return x.MatchNumber
	}
	return 0
}

func (x *JackpotSlips) GetMarketID() int64 {
	if x != nil {
		return x.MarketID
	}
	return 0
}

func (x *JackpotSlips) GetOutcomeID() string {
	if x != nil {
		return x.OutcomeID
	}
	return ""
}

func (x *JackpotSlips) GetSpecifier() string {
	if x != nil {
		return x.Specifier
	}
	return ""
}

type JPBetStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID                   int64                   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Description          string                  `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	Status               int64                   `protobuf:"varint,3,opt,name=Status,proto3" json:"Status,omitempty"`
	Payout               float32                 `protobuf:"fixed32,4,opt,name=Payout,proto3" json:"Payout,omitempty"`
	JackpotSelectedSlips []*JackpotSelectedSlips `protobuf:"bytes,5,rep,name=JackpotSelectedSlips,proto3" json:"JackpotSelectedSlips,omitempty"`
	JackpotID            int64                   `protobuf:"varint,6,opt,name=JackpotID,proto3" json:"JackpotID,omitempty"`
}

func (x *JPBetStatusResponse) Reset() {
	*x = JPBetStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jackpot_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JPBetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JPBetStatusResponse) ProtoMessage() {}

func (x *JPBetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jackpot_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JPBetStatusResponse.ProtoReflect.Descriptor instead.
func (*JPBetStatusResponse) Descriptor() ([]byte, []int) {
	return file_jackpot_service_proto_rawDescGZIP(), []int{9}
}

func (x *JPBetStatusResponse) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *JPBetStatusResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *JPBetStatusResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *JPBetStatusResponse) GetPayout() float32 {
	if x != nil {
		return x.Payout
	}
	return 0
}

func (x *JPBetStatusResponse) GetJackpotSelectedSlips() []*JackpotSelectedSlips {
	if x != nil {
		return x.JackpotSelectedSlips
	}
	return nil
}

func (x *JPBetStatusResponse) GetJackpotID() int64 {
	if x != nil {
		return x.JackpotID
	}
	return 0
}

type JPBetStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProfileID int64  `protobuf:"varint,1,opt,name=profileID,proto3" json:"profileID,omitempty"`
	ShareCode string `protobuf:"bytes,2,opt,name=ShareCode,proto3" json:"ShareCode,omitempty"`
}

func (x *JPBetStatusRequest) Reset() {
	*x = JPBetStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jackpot_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JPBetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JPBetStatusRequest) ProtoMessage() {}

func (x *JPBetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jackpot_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JPBetStatusRequest.ProtoReflect.Descriptor instead.
func (*JPBetStatusRequest) Descriptor() ([]byte, []int) {
	return file_jackpot_service_proto_rawDescGZIP(), []int{10}
}

func (x *JPBetStatusRequest) GetProfileID() int64 {
	if x != nil {
		return x.ProfileID
	}
	return 0
}

func (x *JPBetStatusRequest) GetShareCode() string {
	if x != nil {
		return x.ShareCode
	}
	return ""
}

type PlaceBetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status      int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ShareCode   string `protobuf:"bytes,3,opt,name=shareCode,proto3" json:"shareCode,omitempty"`
}

func (x *PlaceBetResponse) Reset() {
	*x = PlaceBetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jackpot_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaceBetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceBetResponse) ProtoMessage() {}

func (x *PlaceBetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jackpot_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceBetResponse.ProtoReflect.Descriptor instead.
func (*PlaceBetResponse) Descriptor() ([]byte, []int) {
	return file_jackpot_service_proto_rawDescGZIP(), []int{11}
}

func (x *PlaceBetResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PlaceBetResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PlaceBetResponse) GetShareCode() string {
	if x != nil {
		return x.ShareCode
	}
	return ""
}

type AutoPickRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProfileID int64   `protobuf:"varint,1,opt,name=ProfileID,proto3" json:"ProfileID,omitempty"`
	Stake     float32 `protobuf:"fixed32,2,opt,name=stake,proto3" json:"stake,omitempty"`
	IpAddress string  `protobuf:"bytes,3,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	JackpotID int64   `protobuf:"varint,4,opt,name=JackpotID,proto3" json:"JackpotID,omitempty"`
}

func (x *AutoPickRequest) Reset() {
	*x = AutoPickRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jackpot_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AutoPickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoPickRequest) ProtoMessage() {}

func (x *AutoPickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jackpot_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoPickRequest.ProtoReflect.Descriptor instead.
func (*AutoPickRequest) Descriptor() ([]byte, []int) {
	return file_jackpot_service_proto_rawDescGZIP(), []int{12}
}

func (x *AutoPickRequest) GetProfileID() int64 {
	if x != nil {
		return x.ProfileID
	}
	return 0
}

func (x *AutoPickRequest) GetStake() float32 {
	if x != nil {
		return x.Stake
	}
	return 0
}

func (x *AutoPickRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *AutoPickRequest) GetJackpotID() int64 {
	if x != nil {
		return x.JackpotID
	}
	return 0
}

type AliasPickRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProfileID int64   `protobuf:"varint,1,opt,name=ProfileID,proto3" json:"ProfileID,omitempty"`
	Stake     float32 `protobuf:"fixed32,2,opt,name=stake,proto3" json:"stake,omitempty"`
	IpAddress string  `protobuf:"bytes,3,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	JackpotID int64   `protobuf:"varint,4,opt,name=JackpotID,proto3" json:"JackpotID,omitempty"`
	Alias     string  `protobuf:"bytes,5,opt,name=Alias,proto3" json:"Alias,omitempty"`
}

func (x *AliasPickRequest) Reset() {
	*x = AliasPickRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jackpot_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AliasPickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliasPickRequest) ProtoMessage() {}

func (x *AliasPickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jackpot_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliasPickRequest.ProtoReflect.Descriptor instead.
func (*AliasPickRequest) Descriptor() ([]byte, []int) {
	return file_jackpot_service_proto_rawDescGZIP(), []int{13}
}

func (x *AliasPickRequest) GetProfileID() int64 {
	if x != nil {
		return x.ProfileID
	}
	return 0
}

func (x *AliasPickRequest) GetStake() float32 {
	if x != nil {
		return x.Stake
	}
	return 0
}

func (x *AliasPickRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *AliasPickRequest) GetJackpotID() int64 {
	if x != nil {
		return x.JackpotID
	}
	return 0
}

func (x *AliasPickRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

var File_jackpot_service_proto protoreflect.FileDescriptor

var file_jackpot_service_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6a, 0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x22, 0x0d, 0x0a, 0x0b, 0x4a, 0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74, 0x50, 0x69, 0x6e, 0x67,
	0x22, 0x39, 0x0a, 0x0b, 0x4a, 0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74, 0x50, 0x6f, 0x6e, 0x67, 0x12,
	0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x33, 0x0a, 0x13, 0x4a,
	0x50, 0x42, 0x65, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x44,
	0x22, 0x6a, 0x0a, 0x14, 0x4a, 0x50, 0x42, 0x65, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x4f, 0x66, 0x42, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x42, 0x65, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x53, 0x74, 0x61, 0x6b, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x53, 0x74, 0x61,
	0x6b, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x57, 0x69, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x07, 0x57, 0x69, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x22, 0x6e, 0x0a, 0x14,
	0x4a, 0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x53,
	0x6c, 0x69, 0x70, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x93, 0x02, 0x0a,
	0x11, 0x4a, 0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74, 0x42, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x3a, 0x0a, 0x0c, 0x4a, 0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74, 0x53, 0x6c, 0x69,
	0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x4a, 0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74, 0x53, 0x6c, 0x69, 0x70, 0x73,
	0x52, 0x0c, 0x4a, 0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74, 0x53, 0x6c, 0x69, 0x70, 0x73, 0x12, 0x1c,
	0x0a, 0x09, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x6b, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x6b, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x70,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69,
	0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x65, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x62, 0x65, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x64,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4a, 0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74, 0x49,
	0x44, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x4a, 0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74,
	0x49, 0x44, 0x22, 0x35, 0x0a, 0x13, 0x4a, 0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74, 0x47, 0x61, 0x6d,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x44, 0x22, 0x2c, 0x0a, 0x14, 0x4a, 0x61, 0x63,
	0x6b, 0x70, 0x6f, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x47, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x47, 0x61, 0x6d, 0x65, 0x73, 0x22, 0xc2, 0x01, 0x0a, 0x0c, 0x4a, 0x61, 0x63, 0x6b,
	0x70, 0x6f, 0x74, 0x53, 0x6c, 0x69, 0x70, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x61, 0x74, 0x63,
	0x68, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x49, 0x44,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x49, 0x44,
	0x12, 0x1c, 0x0a, 0x09, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x49, 0x44, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x49, 0x44, 0x12, 0x1c,
	0x0a, 0x09, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x72, 0x22, 0xe9, 0x01, 0x0a,
	0x13, 0x4a, 0x50, 0x42, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x50, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06,
	0x50, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x12, 0x52, 0x0a, 0x14, 0x4a, 0x61, 0x63, 0x6b, 0x70, 0x6f,
	0x74, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x53, 0x6c, 0x69, 0x70, 0x73, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x4a, 0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x53,
	0x6c, 0x69, 0x70, 0x73, 0x52, 0x14, 0x4a, 0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74, 0x53, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x65, 0x64, 0x53, 0x6c, 0x69, 0x70, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x4a, 0x61,
	0x63, 0x6b, 0x70, 0x6f, 0x74, 0x49, 0x44, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x4a,
	0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74, 0x49, 0x44, 0x22, 0x50, 0x0a, 0x12, 0x4a, 0x50, 0x42, 0x65,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09,
	0x53, 0x68, 0x61, 0x72, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x53, 0x68, 0x61, 0x72, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x6a, 0x0a, 0x10, 0x50, 0x6c,
	0x61, 0x63, 0x65, 0x42, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x68, 0x61, 0x72,
	0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x61,
	0x72, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x81, 0x01, 0x0a, 0x0f, 0x41, 0x75, 0x74, 0x6f, 0x50,
	0x69, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x50,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x6b,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x74, 0x61, 0x6b, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x69, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x69, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09,
	0x4a, 0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x4a, 0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74, 0x49, 0x44, 0x22, 0x98, 0x01, 0x0a, 0x10, 0x41,
	0x6c, 0x69, 0x61, 0x73, 0x50, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x6b, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x6b, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x1c, 0x0a, 0x09, 0x4a, 0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74, 0x49, 0x44, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x4a, 0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74, 0x49, 0x44, 0x12,
	0x14, 0x0a, 0x05, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x41, 0x6c, 0x69, 0x61, 0x73, 0x32, 0x84, 0x04, 0x0a, 0x07, 0x4a, 0x61, 0x63, 0x6b, 0x70, 0x6f,
	0x74, 0x12, 0x54, 0x0a, 0x11, 0x4a, 0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74, 0x42, 0x65, 0x74, 0x53,
	0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x4a, 0x50, 0x42, 0x65, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x4a, 0x50, 0x42, 0x65, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x63, 0x65,
	0x42, 0x65, 0x74, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4a,
	0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74, 0x42, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x50, 0x6c, 0x61, 0x63,
	0x65, 0x42, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c,
	0x0a, 0x0b, 0x4a, 0x50, 0x42, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4a, 0x50, 0x42, 0x65, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4a, 0x50, 0x42, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x08,
	0x41, 0x75, 0x74, 0x6f, 0x50, 0x69, 0x63, 0x6b, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x41, 0x75, 0x74, 0x6f, 0x50, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x50,
	0x6c, 0x61, 0x63, 0x65, 0x42, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x45, 0x0a, 0x09, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x50, 0x69, 0x63, 0x6b, 0x12, 0x1a,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x50,
	0x69, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x42, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x07, 0x4a, 0x70, 0x47, 0x61,
	0x6d, 0x65, 0x73, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4a,
	0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4a, 0x61,
	0x63, 0x6b, 0x70, 0x6f, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x15, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4a, 0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74, 0x50,
	0x69, 0x6e, 0x67, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4a,
	0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74, 0x50, 0x6f, 0x6e, 0x67, 0x22, 0x00, 0x42, 0x38, 0x5a, 0x36,
	0x62, 0x69, 0x74, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x6d, 0x61,
	0x79, 0x62, 0x65, 0x74, 0x73, 0x2f, 0x6a, 0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74, 0x2d, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6a,
	0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_jackpot_service_proto_rawDescOnce sync.Once
	file_jackpot_service_proto_rawDescData = file_jackpot_service_proto_rawDesc
)

func file_jackpot_service_proto_rawDescGZIP() []byte {
	file_jackpot_service_proto_rawDescOnce.Do(func() {
		file_jackpot_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_jackpot_service_proto_rawDescData)
	})
	return file_jackpot_service_proto_rawDescData
}

var file_jackpot_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_jackpot_service_proto_goTypes = []any{
	(*JackpotPing)(nil),          // 0: protobuf.JackpotPing
	(*JackpotPong)(nil),          // 1: protobuf.JackpotPong
	(*JPBetSummaryRequest)(nil),  // 2: protobuf.JPBetSummaryRequest
	(*JPBetSummaryResponse)(nil), // 3: protobuf.JPBetSummaryResponse
	(*JackpotSelectedSlips)(nil), // 4: protobuf.JackpotSelectedSlips
	(*JackpotBetRequest)(nil),    // 5: protobuf.JackpotBetRequest
	(*JackpotGamesRequest)(nil),  // 6: protobuf.JackpotGamesRequest
	(*JackpotGamesResponse)(nil), // 7: protobuf.JackpotGamesResponse
	(*JackpotSlips)(nil),         // 8: protobuf.JackpotSlips
	(*JPBetStatusResponse)(nil),  // 9: protobuf.JPBetStatusResponse
	(*JPBetStatusRequest)(nil),   // 10: protobuf.JPBetStatusRequest
	(*PlaceBetResponse)(nil),     // 11: protobuf.PlaceBetResponse
	(*AutoPickRequest)(nil),      // 12: protobuf.AutoPickRequest
	(*AliasPickRequest)(nil),     // 13: protobuf.AliasPickRequest
}
var file_jackpot_service_proto_depIdxs = []int32{
	8,  // 0: protobuf.JackpotBetRequest.JackpotSlips:type_name -> protobuf.JackpotSlips
	4,  // 1: protobuf.JPBetStatusResponse.JackpotSelectedSlips:type_name -> protobuf.JackpotSelectedSlips
	2,  // 2: protobuf.Jackpot.JackpotBetSummary:input_type -> protobuf.JPBetSummaryRequest
	5,  // 3: protobuf.Jackpot.PlaceBet:input_type -> protobuf.JackpotBetRequest
	10, // 4: protobuf.Jackpot.JPBetStatus:input_type -> protobuf.JPBetStatusRequest
	12, // 5: protobuf.Jackpot.AutoPick:input_type -> protobuf.AutoPickRequest
	13, // 6: protobuf.Jackpot.AliasPick:input_type -> protobuf.AliasPickRequest
	6,  // 7: protobuf.Jackpot.JpGames:input_type -> protobuf.JackpotGamesRequest
	0,  // 8: protobuf.Jackpot.Ping:input_type -> protobuf.JackpotPing
	3,  // 9: protobuf.Jackpot.JackpotBetSummary:output_type -> protobuf.JPBetSummaryResponse
	11, // 10: protobuf.Jackpot.PlaceBet:output_type -> protobuf.PlaceBetResponse
	9,  // 11: protobuf.Jackpot.JPBetStatus:output_type -> protobuf.JPBetStatusResponse
	11, // 12: protobuf.Jackpot.AutoPick:output_type -> protobuf.PlaceBetResponse
	11, // 13: protobuf.Jackpot.AliasPick:output_type -> protobuf.PlaceBetResponse
	7,  // 14: protobuf.Jackpot.JpGames:output_type -> protobuf.JackpotGamesResponse
	1,  // 15: protobuf.Jackpot.Ping:output_type -> protobuf.JackpotPong
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_jackpot_service_proto_init() }
func file_jackpot_service_proto_init() {
	if File_jackpot_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jackpot_service_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*JackpotPing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jackpot_service_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*JackpotPong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jackpot_service_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*JPBetSummaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jackpot_service_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*JPBetSummaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jackpot_service_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*JackpotSelectedSlips); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jackpot_service_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*JackpotBetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jackpot_service_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*JackpotGamesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jackpot_service_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*JackpotGamesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jackpot_service_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*JackpotSlips); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jackpot_service_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*JPBetStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jackpot_service_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*JPBetStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jackpot_service_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*PlaceBetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jackpot_service_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*AutoPickRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jackpot_service_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*AliasPickRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jackpot_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jackpot_service_proto_goTypes,
		DependencyIndexes: file_jackpot_service_proto_depIdxs,
		MessageInfos:      file_jackpot_service_proto_msgTypes,
	}.Build()
	File_jackpot_service_proto = out.File
	file_jackpot_service_proto_rawDesc = nil
	file_jackpot_service_proto_goTypes = nil
	file_jackpot_service_proto_depIdxs = nil
}
