// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: odds-service.proto

package odds

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Odds_GetOdds_FullMethodName           = "/protobuf.Odds/GetOdds"
	Odds_GetOutcome_FullMethodName        = "/protobuf.Odds/GetOutcome"
	Odds_GetMarket_FullMethodName         = "/protobuf.Odds/GetMarket"
	Odds_GetProducerStatus_FullMethodName = "/protobuf.Odds/GetProducerStatus"
	Odds_GetProbability_FullMethodName    = "/protobuf.Odds/GetProbability"
	Odds_Ping_FullMethodName              = "/protobuf.Odds/Ping"
)

// OddsClient is the client API for Odds service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OddsClient interface {
	// Sends GetOdds status request
	GetOdds(ctx context.Context, in *GetOddsRequest, opts ...grpc.CallOption) (*GetOddsReply, error)
	GetOutcome(ctx context.Context, in *GetOutcomeRequest, opts ...grpc.CallOption) (*GetOutcomeReply, error)
	GetMarket(ctx context.Context, in *GetMarketRequest, opts ...grpc.CallOption) (*Market, error)
	GetProducerStatus(ctx context.Context, in *ProducerStatusRequest, opts ...grpc.CallOption) (*ProducerStatusReply, error)
	GetProbability(ctx context.Context, in *GetOddsRequest, opts ...grpc.CallOption) (*Probability, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongRequest, error)
}

type oddsClient struct {
	cc grpc.ClientConnInterface
}

func NewOddsClient(cc grpc.ClientConnInterface) OddsClient {
	return &oddsClient{cc}
}

func (c *oddsClient) GetOdds(ctx context.Context, in *GetOddsRequest, opts ...grpc.CallOption) (*GetOddsReply, error) {
	out := new(GetOddsReply)
	err := c.cc.Invoke(ctx, Odds_GetOdds_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oddsClient) GetOutcome(ctx context.Context, in *GetOutcomeRequest, opts ...grpc.CallOption) (*GetOutcomeReply, error) {
	out := new(GetOutcomeReply)
	err := c.cc.Invoke(ctx, Odds_GetOutcome_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oddsClient) GetMarket(ctx context.Context, in *GetMarketRequest, opts ...grpc.CallOption) (*Market, error) {
	out := new(Market)
	err := c.cc.Invoke(ctx, Odds_GetMarket_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oddsClient) GetProducerStatus(ctx context.Context, in *ProducerStatusRequest, opts ...grpc.CallOption) (*ProducerStatusReply, error) {
	out := new(ProducerStatusReply)
	err := c.cc.Invoke(ctx, Odds_GetProducerStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oddsClient) GetProbability(ctx context.Context, in *GetOddsRequest, opts ...grpc.CallOption) (*Probability, error) {
	out := new(Probability)
	err := c.cc.Invoke(ctx, Odds_GetProbability_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oddsClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongRequest, error) {
	out := new(PongRequest)
	err := c.cc.Invoke(ctx, Odds_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OddsServer is the server API for Odds service.
// All implementations must embed UnimplementedOddsServer
// for forward compatibility
type OddsServer interface {
	// Sends GetOdds status request
	GetOdds(context.Context, *GetOddsRequest) (*GetOddsReply, error)
	GetOutcome(context.Context, *GetOutcomeRequest) (*GetOutcomeReply, error)
	GetMarket(context.Context, *GetMarketRequest) (*Market, error)
	GetProducerStatus(context.Context, *ProducerStatusRequest) (*ProducerStatusReply, error)
	GetProbability(context.Context, *GetOddsRequest) (*Probability, error)
	Ping(context.Context, *PingRequest) (*PongRequest, error)
	mustEmbedUnimplementedOddsServer()
}

// UnimplementedOddsServer must be embedded to have forward compatible implementations.
type UnimplementedOddsServer struct {
}

func (UnimplementedOddsServer) GetOdds(context.Context, *GetOddsRequest) (*GetOddsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOdds not implemented")
}
func (UnimplementedOddsServer) GetOutcome(context.Context, *GetOutcomeRequest) (*GetOutcomeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOutcome not implemented")
}
func (UnimplementedOddsServer) GetMarket(context.Context, *GetMarketRequest) (*Market, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMarket not implemented")
}
func (UnimplementedOddsServer) GetProducerStatus(context.Context, *ProducerStatusRequest) (*ProducerStatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProducerStatus not implemented")
}
func (UnimplementedOddsServer) GetProbability(context.Context, *GetOddsRequest) (*Probability, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProbability not implemented")
}
func (UnimplementedOddsServer) Ping(context.Context, *PingRequest) (*PongRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedOddsServer) mustEmbedUnimplementedOddsServer() {}

// UnsafeOddsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OddsServer will
// result in compilation errors.
type UnsafeOddsServer interface {
	mustEmbedUnimplementedOddsServer()
}

func RegisterOddsServer(s grpc.ServiceRegistrar, srv OddsServer) {
	s.RegisterService(&Odds_ServiceDesc, srv)
}

func _Odds_GetOdds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOddsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OddsServer).GetOdds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Odds_GetOdds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OddsServer).GetOdds(ctx, req.(*GetOddsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Odds_GetOutcome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOutcomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OddsServer).GetOutcome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Odds_GetOutcome_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OddsServer).GetOutcome(ctx, req.(*GetOutcomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Odds_GetMarket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OddsServer).GetMarket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Odds_GetMarket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OddsServer).GetMarket(ctx, req.(*GetMarketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Odds_GetProducerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProducerStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OddsServer).GetProducerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Odds_GetProducerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OddsServer).GetProducerStatus(ctx, req.(*ProducerStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Odds_GetProbability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOddsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OddsServer).GetProbability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Odds_GetProbability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OddsServer).GetProbability(ctx, req.(*GetOddsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Odds_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OddsServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Odds_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OddsServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Odds_ServiceDesc is the grpc.ServiceDesc for Odds service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Odds_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Odds",
	HandlerType: (*OddsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOdds",
			Handler:    _Odds_GetOdds_Handler,
		},
		{
			MethodName: "GetOutcome",
			Handler:    _Odds_GetOutcome_Handler,
		},
		{
			MethodName: "GetMarket",
			Handler:    _Odds_GetMarket_Handler,
		},
		{
			MethodName: "GetProducerStatus",
			Handler:    _Odds_GetProducerStatus_Handler,
		},
		{
			MethodName: "GetProbability",
			Handler:    _Odds_GetProbability_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Odds_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "odds-service.proto",
}
