CREATE TABLE safaricom_inbox (
                                 id int(11) NOT NULL AUTO_INCREMENT,
                                 offer_code varchar(100) NOT NULL,
                                 message varchar(1000) NOT NULL,
                                 request_id varchar(100) DEFAULT NULL,
                                 operation varchar(100) DEFAULT NULL,
                                 request_timestamp bigint(50) DEFAULT NULL,
                                 refernce_id varchar(100) DEFAULT NULL,
                                 msisdn bigint(20) NOT NULL,
                                 status int(11) NOT NULL DEFAULT 0,
                                 link_id varchar(200) NOT NULL,
                                 command varchar(100) DEFAULT NULL,
                                 created datetime NOT NULL DEFAULT current_timestamp(),
                                 updated timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
                                 PRIMARY KEY (id),
                                 UNIQUE KEY request_id (request_id),
                                 KEY safaricom_inbox_status (status),
                                 KEY safaricom_inbox_link_id (link_id),
                                 KEY safaricom_inbox_created (created),
                                 KEY safaricom_inbox_offer_code (offer_code),
                                 KEY safaricom_inbox_msisdn (msisdn),
                                 KEY safaricom_inbox_command (command),
                                 FULLTEXT KEY safaricom_inbox_message (message)
);
