package constants

const BETSLIP_PROCESSING_PENDING = 0
const BETSLIP_PROCESSING_SETTLED = 1
const BETSLIP_PROCESSING_COMPLETED = 2
const BETSLIP_PROCESSING_CANCELLED = -1
const BETSLIP_PROCESSING_VOIDED = 3


// won column name
const STATUS_NOT_LOST_OR_WON = -1
const STATUS_WON = 1
const STATUS_LOST = 0
const STATUS_CASHOUT = 4
const STATUS_PARTIAL_CASHOUT = 5
const STATUS_CANCELLED = 6

const BET_PENDING = 0
const BET_LOST = 1
const BET_WON = 2
const BET_VOIDED = 3
const BET_CANCELLED = -1
const BET_CASHOUT  = 5